return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "elm",
      "haskell",
      "swift",
      "bash",
      "diff",
      "comment",
      "regex",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "css",
      "html",
      "javascript",
      "typescript",
      "tsx",
      "json",
      "yaml",
      "toml",
      "markdown",
      "markdown_inline",
      "lua",
      "luadoc",
      "luap",
      "python",
    },
  },
}
